--Creating the tables

CREATE TABLE Tokens (
	Name VARCHAR(20) NOT NULL,
	PRIMARY KEY (Name)
);

CREATE TABLE Locations (
	ID INT NOT NULL,
	Name VARCHAR(20) NOT NULL,
	Type VARCHAR(10) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE Players (
	ID INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Token VARCHAR(20) NOT NULL UNIQUE,
	Balance INT NOT NULL DEFAULT 200,
	Location INT NOT NULL DEFAULT 1,
	IsSuspended BOOLEAN NOT NULL DEFAULT 0,
	DieRoll INT NOT NULL DEFAULT 0,
	PRIMARY KEY (ID),
	FOREIGN KEY (Token) REFERENCES Tokens (Name),
	FOREIGN KEY (Location) REFERENCES Locations (ID)
);

CREATE TABLE Buildings (
	ID INT NOT NULL,
	TuitionFee INT NOT NULL,
	Owner VARCHAR(20) DEFAULT NULL,
	IsSameOwner BOOLEAN NOT NULL DEFAULT 0,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID) REFERENCES Locations (ID),
	FOREIGN KEY (Owner) REFERENCES Tokens (Name)
);

CREATE TABLE Specials (
	ID INT NOT NULL,
	Description VARCHAR(80) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID) REFERENCES Locations (ID)
);

CREATE TABLE Audit_Trails (
	PlayerID INT NOT NULL,
	Location INT NOT NULL DEFAULT 1,
	Balance INT NOT NULL DEFAULT  200,
	GameRound INT NOT NULL,
	PRIMARY KEY (PlayerID, GameRound),
	FOREIGN KEY (PlayerID) REFERENCES Players (ID),
	FOREIGN KEY (Location) REFERENCES Locations (ID)
);